import os
from datetime import datetime
import pandas as pd 

log = 'log/'+datetime.today().date().isoformat()+'/log.csv'

print(datetime.now().strftime('%d/%m/%Y %H:%M'))
from win32com.client import Dispatch
obj = Dispatch('Outlook.Application')
mail = obj.CreateItem(0)
mail.Subject = 'Report of Received CQCs '
mail.Save()

'''
field = [
                        'lineitemforms['+i+'].strfailNo',
                        'lineitemforms['+i+'].strIncidentType',
                        'lineitemforms['+i+'].strEditAccess',
                        'lineitemforms['+i+'].strPhase',
                        'lineitemforms['+i+'].strCorrActNo',
                        'lineitemforms['+i+'].strstrLineItemId',
                        'lineitemforms['+i+'].strTNIAccess',
                        'lineitemforms['+i+'].strRootCauseProposer',
                        'lineitemforms['+i+'].strLineItemDate',
                        'lineitemforms['+i+'].strLineItemNo',
                        'lineitemforms['+i+'].strIncidentNo',
                        'lineitemforms['+i+'].strdelchk',
                        'lineitemforms['+i+'].strrcvchk',
                        'lineitemforms['+i+'].strLineItemType',
                        'lineitemforms['+i+'].strCustReason',
                        'lineitemforms['+i+'].strABADone',
                        'lineitemforms['+i+'].strABAhelpMessage',
                        'lineitemforms['+i+'].strABAComments',
                        'lineitemforms['+i+'].strFqeCustDesc',
                        'lineitemforms['+i+'].strhelpMessage',
                        'lineitemforms['+i+'].strFqeComments',
                        'lineitemforms['+i+'].strCqeCustDesc',
                        'lineitemforms['+i+'].strCqehelpMessage',
                        'lineitemforms['+i+'].strCqeComments',
                        'lineitemforms['+i+'].strCustRef',
                        'lineitemforms['+i+'].strPrototype',
                        'lineitemforms['+i+'].strMileage',
                        'lineitemforms['+i+'].strEndCustCode',
                        'lineitemforms['+i+'].strCustBuildLoc',
                        'lineitemforms['+i+'].strECUManufacturingDate',
                        'lineitemforms['+i+'].strTraceCode',
                        'lineitemforms['+i+'].strSysCdeInit',
                        'lineitemforms['+i+'].strSysCdeValDB',
                        'lineitemforms['+i+'].strSysCdeDrpInit',
                        'lineitemforms['+i+'].strSysCdeDrpDb',
                        'lineitemforms['+i+'].strSysCdeTxtInit',
                        'lineitemforms['+i+'].strSysCdeTxtDb',
                        'lineitemforms['+i+'].strReturnCode',
                        'lineitemforms['+i+'].strFirstNo',
                        'lineitemforms['+i+'].strFirstYes',
                        'lineitemforms['+i+'].strSecondNo',
                        'lineitemforms['+i+'].strSecondYes',
                        'lineitemforms['+i+'].strUserAct',
                        'lineitemforms['+i+'].strRequestId',
                        'lineitemforms['+i+'].strRequestStatus',
                        'lineitemforms['+i+'].strSysCodeTxt',
                        'lineitemforms['+i+'].strEmptyCol',
                        'lineitemforms['+i+'].strSysCodeDisp',
                        'lineitemforms['+i+'].strDateCode',
                        'lineitemforms['+i+'].strTestMarkedDateCode',
                        'lineitemforms['+i+'].strBackMark',
                        'lineitemforms['+i+'].strMaskSet',
                        'lineitemforms['+i+'].strLineItemQty',
                        'lineitemforms['+i+'].strCustSerialNo',
                        'lineitemforms['+i+'].strLineItemComm',
                        'lineitemforms['+i+'].strFabSite',
                        'lineitemforms['+i+'].strWaferLotNo',
                        'lineitemforms['+i+'].strFabOutDate',
                        'lineitemforms['+i+'].strProbeSite',
                        'lineitemforms['+i+'].strProbeDate',
                        'lineitemforms['+i+'].strAssySite',
                        'lineitemforms['+i+'].strAssyLotNo',
                        'lineitemforms['+i+'].strAssyOutDate',
                        'lineitemforms['+i+'].strTestSite',
                        'lineitemforms['+i+'].strTestLotNo',
                        'lineitemforms['+i+'].strTestOutDate',
                        'lineitemforms['+i+'].strQtyRcvd',
                        'lineitemforms['+i+'].strLineRcvDate',
                        'lineitemforms['+i+'].strRcvUserId',
                        'lineitemforms['+i+'].strPbmVrfd',
                        'lineitemforms['+i+'].strCauseCode',
                        'lineitemforms['+i+'].strWaferTechCode',
                        'lineitemforms['+i+'].strWaferTechDesc',
                        'lineitemforms['+i+'].strFFVSummary',
                        'lineitemforms['+i+'].strEVALSummary',
                        'lineitemforms['+i+'].strFailMode',
                        'lineitemforms['+i+'].strSfaParent',
                        'lineitemforms['+i+'].strSFA',
                        'lineitemforms['+i+'].strDefectType',
                        'lineitemforms['+i+'].strDefectTypeDesc',
                        'lineitemforms['+i+'].strFailMechOccur',
                        'lineitemforms['+i+'].strRootCauseOccur',
                        'lineitemforms['+i+'].strFailMechEscp',
                        'lineitemforms['+i+'].strRootCauseEscape',
                        'lineitemforms['+i+'].strFailCode',
                        'lineitemforms['+i+'].strFailCodeDesc',
                        'lineitemforms['+i+'].strRootCauseOccurDesc',
                        'lineitemforms['+i+'].strRootCauseEscapeDesc',
                        'lineitemforms['+i+'].strPASumm',
                        'lineitemforms['+i+'].strCorrActNo',
                        'lineitemforms['+i+'].straimsno',
                        'lineitemforms['+i+'].strPAReport',
                        'lineitemforms['+i+'].strLSAaimsno',
                        'lineitemforms['+i+'].strRepeatOccur',
                        'lineitemforms['+i+'].strFuncSafetyIssue',
                        'lineitemforms['+i+'].strCustFunSafetyRelIssue'
                    ]
'''