# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\nxf44756\OneDrive - NXP\Desktop\Gadgets\COTS\source\COTS\barcode.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(790, 400)
        Dialog.setMinimumSize(QtCore.QSize(790, 400))
        Dialog.setMaximumSize(QtCore.QSize(790, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/resources/img/Scanner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.backButton = QtWidgets.QPushButton(Dialog)
        self.backButton.setGeometry(QtCore.QRect(630, 10, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.backButton.setObjectName("backButton")
        self.cqcnumInput = QtWidgets.QLineEdit(Dialog)
        self.cqcnumInput.setGeometry(QtCore.QRect(50, 280, 241, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.cqcnumInput.setFont(font)
        self.cqcnumInput.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cqcnumInput.setText("")
        self.cqcnumInput.setMaxLength(7)
        self.cqcnumInput.setAlignment(QtCore.Qt.AlignCenter)
        self.cqcnumInput.setObjectName("cqcnumInput")
        self.barcodeGenButton = QtWidgets.QPushButton(Dialog)
        self.barcodeGenButton.setGeometry(QtCore.QRect(310, 290, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.barcodeGenButton.setFont(font)
        self.barcodeGenButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.barcodeGenButton.setObjectName("barcodeGenButton")
        self.cqcnumOutput = QtWidgets.QLineEdit(Dialog)
        self.cqcnumOutput.setGeometry(QtCore.QRect(50, 90, 721, 141))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.cqcnumOutput.setFont(font)
        self.cqcnumOutput.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cqcnumOutput.setText("")
        self.cqcnumOutput.setMaxLength(7)
        self.cqcnumOutput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cqcnumOutput.setClearButtonEnabled(True)
        self.cqcnumOutput.setObjectName("cqcnumOutput")
        self.inputLabel = QtWidgets.QLabel(Dialog)
        self.inputLabel.setGeometry(QtCore.QRect(50, 250, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inputLabel.setFont(font)
        self.inputLabel.setObjectName("inputLabel")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 50, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.barcodeDisplay = QtWidgets.QLabel(Dialog)
        self.barcodeDisplay.setGeometry(QtCore.QRect(500, 250, 271, 111))
        self.barcodeDisplay.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.barcodeDisplay.setText("")
        self.barcodeDisplay.setScaledContents(True)
        self.barcodeDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.barcodeDisplay.setObjectName("barcodeDisplay")

        self.retranslateUi(Dialog)
        self.backButton.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Barcode Scanner"))
        self.backButton.setText(_translate("Dialog", "Back to Menu"))
        self.barcodeGenButton.setText(_translate("Dialog", "Generate\n"
"Barcode"))
        self.inputLabel.setText(_translate("Dialog", "Please input CQC number"))
        self.label.setText(_translate("Dialog", "Click the box below and scan the CQC barcode"))
import barcode_resource_rc
