# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\nxf44756\OneDrive - NXP\Desktop\Gadgets\COTS\source\COTS\checkout.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(380, 360)
        Dialog.setMinimumSize(QtCore.QSize(380, 0))
        Dialog.setMaximumSize(QtCore.QSize(380, 400))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/resources/img/Checkout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(220, 10, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setObjectName("pushButton")
        self.checkOutButton = QtWidgets.QPushButton(Dialog)
        self.checkOutButton.setGeometry(QtCore.QRect(210, 220, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.checkOutButton.setFont(font)
        self.checkOutButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkOutButton.setIcon(icon)
        self.checkOutButton.setIconSize(QtCore.QSize(60, 60))
        self.checkOutButton.setObjectName("checkOutButton")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 60, 391, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.destEdit = QtWidgets.QComboBox(Dialog)
        self.destEdit.setGeometry(QtCore.QRect(210, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.destEdit.setFont(font)
        self.destEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.destEdit.setEditable(False)
        self.destEdit.setObjectName("destEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 260, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(20, 80, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_1.setObjectName("label_1")
        self.cqcNumEdit = QtWidgets.QLineEdit(Dialog)
        self.cqcNumEdit.setGeometry(QtCore.QRect(20, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.cqcNumEdit.setFont(font)
        self.cqcNumEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cqcNumEdit.setText("")
        self.cqcNumEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cqcNumEdit.setObjectName("cqcNumEdit")
        self.peEdit = QtWidgets.QLineEdit(Dialog)
        self.peEdit.setGeometry(QtCore.QRect(20, 280, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.peEdit.setFont(font)
        self.peEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.peEdit.setText("")
        self.peEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.peEdit.setObjectName("peEdit")
        self.cqeEdit = QtWidgets.QLineEdit(Dialog)
        self.cqeEdit.setGeometry(QtCore.QRect(20, 220, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.cqeEdit.setFont(font)
        self.cqeEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cqeEdit.setText("")
        self.cqeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cqeEdit.setObjectName("cqeEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.partNameEdit = QtWidgets.QLineEdit(Dialog)
        self.partNameEdit.setGeometry(QtCore.QRect(20, 160, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.partNameEdit.setFont(font)
        self.partNameEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.partNameEdit.setText("")
        self.partNameEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.partNameEdit.setObjectName("partNameEdit")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(210, 80, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.listenerButton = QtWidgets.QPushButton(Dialog)
        self.listenerButton.setGeometry(QtCore.QRect(150, 110, 16, 16))
        self.listenerButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.listenerButton.setObjectName("listenerButton")
        self.resultLabel = QtWidgets.QLabel(Dialog)
        self.resultLabel.setGeometry(QtCore.QRect(10, 320, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.resultLabel.setFont(font)
        self.resultLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.resultLabel.setText("")
        self.resultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLabel.setObjectName("resultLabel")
        self.clearButton = QtWidgets.QPushButton(Dialog)
        self.clearButton.setGeometry(QtCore.QRect(210, 160, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.clearButton.setFont(font)
        self.clearButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clearButton.setIconSize(QtCore.QSize(60, 60))
        self.clearButton.setObjectName("clearButton")
        self.listenerButton.raise_()
        self.pushButton.raise_()
        self.checkOutButton.raise_()
        self.line.raise_()
        self.destEdit.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_1.raise_()
        self.cqcNumEdit.raise_()
        self.peEdit.raise_()
        self.cqeEdit.raise_()
        self.label_2.raise_()
        self.partNameEdit.raise_()
        self.label_5.raise_()
        self.resultLabel.raise_()
        self.clearButton.raise_()

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.close)
        self.checkOutButton.clicked.connect(Dialog.checkOut)
        self.destEdit.currentIndexChanged['int'].connect(Dialog.destSelected)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.cqcNumEdit, self.partNameEdit)
        Dialog.setTabOrder(self.partNameEdit, self.cqeEdit)
        Dialog.setTabOrder(self.cqeEdit, self.peEdit)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "CQC Check-out"))
        self.pushButton.setText(_translate("Dialog", "Back to Menu"))
        self.checkOutButton.setText(_translate("Dialog", "Check-out"))
        self.label_3.setText(_translate("Dialog", "Quality Engineer"))
        self.label_4.setText(_translate("Dialog", "Product Engineer"))
        self.label_1.setText(_translate("Dialog", "CQC Number"))
        self.label_2.setText(_translate("Dialog", "Part Name"))
        self.label_5.setText(_translate("Dialog", "Destination"))
        self.listenerButton.setText(_translate("Dialog", "PushButton"))
        self.clearButton.setText(_translate("Dialog", "Clear"))
import checkout_resource_rc
