# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\nxf44756\OneDrive - NXP\Desktop\Gadgets\COTS\source\COTS\lookup.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(860, 370)
        Dialog.setMinimumSize(QtCore.QSize(860, 370))
        Dialog.setMaximumSize(QtCore.QSize(860, 370))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/resources/img/alarm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(690, 10, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 60, 871, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.welcomeLabel = QtWidgets.QLabel(Dialog)
        self.welcomeLabel.setGeometry(QtCore.QRect(10, 20, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.welcomeLabel.setText("")
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.partNameEdit = QtWidgets.QLineEdit(Dialog)
        self.partNameEdit.setGeometry(QtCore.QRect(20, 160, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.partNameEdit.setFont(font)
        self.partNameEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.partNameEdit.setText("")
        self.partNameEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.partNameEdit.setObjectName("partNameEdit")
        self.peEdit = QtWidgets.QLineEdit(Dialog)
        self.peEdit.setGeometry(QtCore.QRect(20, 280, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.peEdit.setFont(font)
        self.peEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.peEdit.setText("")
        self.peEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.peEdit.setObjectName("peEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.cqcNumEdit = QtWidgets.QLineEdit(Dialog)
        self.cqcNumEdit.setGeometry(QtCore.QRect(20, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.cqcNumEdit.setFont(font)
        self.cqcNumEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cqcNumEdit.setText("")
        self.cqcNumEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cqcNumEdit.setObjectName("cqcNumEdit")
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(20, 80, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_1.setObjectName("label_1")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.cqeEdit = QtWidgets.QLineEdit(Dialog)
        self.cqeEdit.setGeometry(QtCore.QRect(20, 220, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.cqeEdit.setFont(font)
        self.cqeEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cqeEdit.setText("")
        self.cqeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cqeEdit.setObjectName("cqeEdit")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 260, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.listenerButton = QtWidgets.QPushButton(Dialog)
        self.listenerButton.setGeometry(QtCore.QRect(160, 110, 16, 16))
        self.listenerButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.listenerButton.setObjectName("listenerButton")
        self.prpBox = QtWidgets.QCheckBox(Dialog)
        self.prpBox.setGeometry(QtCore.QRect(210, 80, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.prpBox.setFont(font)
        self.prpBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prpBox.setChecked(True)
        self.prpBox.setObjectName("prpBox")
        self.tstBox = QtWidgets.QCheckBox(Dialog)
        self.tstBox.setGeometry(QtCore.QRect(210, 110, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tstBox.setFont(font)
        self.tstBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tstBox.setChecked(True)
        self.tstBox.setObjectName("tstBox")
        self.cqcList = QtWidgets.QTableView(Dialog)
        self.cqcList.setGeometry(QtCore.QRect(360, 80, 491, 271))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.cqcList.setFont(font)
        self.cqcList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cqcList.setStyleSheet("QTableView{\n"
"    selection-background-color: rgb(123, 177, 219);\n"
"}\n"
"QHeaderView::section{\n"
"    font: 75 8pt \"Arial\";\n"
"    background-color: rgb(232, 232, 232);\n"
"}")
        self.cqcList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.cqcList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.cqcList.setProperty("showDropIndicator", False)
        self.cqcList.setDragDropOverwriteMode(False)
        self.cqcList.setAlternatingRowColors(False)
        self.cqcList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.cqcList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.cqcList.setSortingEnabled(False)
        self.cqcList.setObjectName("cqcList")
        self.cqcList.horizontalHeader().setCascadingSectionResizes(False)
        self.cqcList.horizontalHeader().setHighlightSections(False)
        self.cqcList.verticalHeader().setVisible(False)
        self.cqcList.verticalHeader().setCascadingSectionResizes(False)
        self.transferButton = QtWidgets.QPushButton(Dialog)
        self.transferButton.setGeometry(QtCore.QRect(210, 140, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.transferButton.setFont(font)
        self.transferButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.transferButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/resources/img/Lookup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.transferButton.setIcon(icon1)
        self.transferButton.setIconSize(QtCore.QSize(40, 40))
        self.transferButton.setCheckable(False)
        self.transferButton.setObjectName("transferButton")
        self.resultLabel = QtWidgets.QLabel(Dialog)
        self.resultLabel.setGeometry(QtCore.QRect(20, 320, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.resultLabel.setFont(font)
        self.resultLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.resultLabel.setText("")
        self.resultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLabel.setObjectName("resultLabel")
        self.emailButton = QtWidgets.QPushButton(Dialog)
        self.emailButton.setGeometry(QtCore.QRect(210, 260, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.emailButton.setFont(font)
        self.emailButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.emailButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.emailButton.setIcon(icon)
        self.emailButton.setIconSize(QtCore.QSize(40, 40))
        self.emailButton.setCheckable(False)
        self.emailButton.setObjectName("emailButton")
        self.clearButton = QtWidgets.QPushButton(Dialog)
        self.clearButton.setGeometry(QtCore.QRect(210, 210, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.clearButton.setFont(font)
        self.clearButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clearButton.setIconSize(QtCore.QSize(60, 60))
        self.clearButton.setObjectName("clearButton")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(340, 70, 20, 311))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.insEdit = QtWidgets.QLineEdit(Dialog)
        self.insEdit.setGeometry(QtCore.QRect(80, 290, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPixelSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.insEdit.setFont(font)
        self.insEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.insEdit.setText("")
        self.insEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.insEdit.setObjectName("insEdit")
        self.insEdit.raise_()
        self.pushButton.raise_()
        self.line.raise_()
        self.welcomeLabel.raise_()
        self.partNameEdit.raise_()
        self.peEdit.raise_()
        self.label_2.raise_()
        self.label_1.raise_()
        self.label_3.raise_()
        self.cqeEdit.raise_()
        self.label_4.raise_()
        self.listenerButton.raise_()
        self.prpBox.raise_()
        self.tstBox.raise_()
        self.cqcList.raise_()
        self.transferButton.raise_()
        self.resultLabel.raise_()
        self.emailButton.raise_()
        self.cqcNumEdit.raise_()
        self.clearButton.raise_()
        self.line_2.raise_()

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.close)
        self.transferButton.clicked.connect(Dialog.transfer)
        self.emailButton.clicked.connect(Dialog.email)
        self.cqcList.doubleClicked['QModelIndex'].connect(Dialog.itemSelected)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.cqcNumEdit, self.partNameEdit)
        Dialog.setTabOrder(self.partNameEdit, self.cqeEdit)
        Dialog.setTabOrder(self.cqeEdit, self.peEdit)
        Dialog.setTabOrder(self.peEdit, self.listenerButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "CQC Transfer"))
        self.pushButton.setText(_translate("Dialog", "Back to Menu"))
        self.label_2.setText(_translate("Dialog", "Part Name"))
        self.label_1.setText(_translate("Dialog", "CQC Number"))
        self.label_3.setText(_translate("Dialog", "Quality Engineer"))
        self.label_4.setText(_translate("Dialog", "Product Engineer"))
        self.listenerButton.setText(_translate("Dialog", "PushButton"))
        self.prpBox.setText(_translate("Dialog", "Close PRP"))
        self.tstBox.setText(_translate("Dialog", "Create TST"))
        self.transferButton.setText(_translate("Dialog", "Transfer"))
        self.emailButton.setText(_translate("Dialog", "Send Email"))
        self.clearButton.setText(_translate("Dialog", "Clear"))
import lookup_resource_rc
import receipt_resource_rc
