# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\nxf44756\OneDrive - NXP\Desktop\Gadgets\COTS\source\COTS\Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(790, 400))
        MainWindow.setMaximumSize(QtCore.QSize(790, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/img/Barcode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(790, 400))
        self.centralwidget.setMaximumSize(QtCore.QSize(790, 400))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.about = QtWidgets.QLabel(self.centralwidget)
        self.about.setGeometry(QtCore.QRect(600, 0, 181, 91))
        self.about.setTextFormat(QtCore.Qt.RichText)
        self.about.setScaledContents(False)
        self.about.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.about.setWordWrap(False)
        self.about.setIndent(0)
        self.about.setObjectName("about")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(640, 320, 151, 81))
        self.logo.setTextFormat(QtCore.Qt.RichText)
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.logo.setObjectName("logo")
        self.userName = QtWidgets.QLineEdit(self.centralwidget)
        self.userName.setGeometry(QtCore.QRect(150, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.userName.setFont(font)
        self.userName.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.userName.setAcceptDrops(False)
        self.userName.setInputMask("")
        self.userName.setMaxLength(9)
        self.userName.setObjectName("userName")
        self.loginLabel = QtWidgets.QLabel(self.centralwidget)
        self.loginLabel.setGeometry(QtCore.QRect(20, 20, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.loginLabel.setFont(font)
        self.loginLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.loginLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.loginLabel.setObjectName("loginLabel")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(150, 60, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password.setFont(font)
        self.password.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.password.setAcceptDrops(False)
        self.password.setInputMask("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(330, 20, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.loginButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.loginButton.setObjectName("loginButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 90, 791, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.receiptButton = QtWidgets.QPushButton(self.centralwidget)
        self.receiptButton.setGeometry(QtCore.QRect(20, 110, 361, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.receiptButton.setFont(font)
        self.receiptButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/img/Receipt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.receiptButton.setIcon(icon1)
        self.receiptButton.setIconSize(QtCore.QSize(50, 50))
        self.receiptButton.setObjectName("receiptButton")
        self.checkoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.checkoutButton.setGeometry(QtCore.QRect(20, 190, 361, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkoutButton.setFont(font)
        self.checkoutButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/img/Checkout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkoutButton.setIcon(icon2)
        self.checkoutButton.setIconSize(QtCore.QSize(50, 50))
        self.checkoutButton.setObjectName("checkoutButton")
        self.reportButton = QtWidgets.QPushButton(self.centralwidget)
        self.reportButton.setEnabled(True)
        self.reportButton.setGeometry(QtCore.QRect(410, 190, 361, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.reportButton.setFont(font)
        self.reportButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/resources/img/Report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reportButton.setIcon(icon3)
        self.reportButton.setIconSize(QtCore.QSize(50, 50))
        self.reportButton.setObjectName("reportButton")
        self.lookupButton = QtWidgets.QPushButton(self.centralwidget)
        self.lookupButton.setEnabled(True)
        self.lookupButton.setGeometry(QtCore.QRect(410, 110, 361, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lookupButton.setFont(font)
        self.lookupButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/resources/img/alarm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lookupButton.setIcon(icon4)
        self.lookupButton.setIconSize(QtCore.QSize(50, 50))
        self.lookupButton.setCheckable(False)
        self.lookupButton.setObjectName("lookupButton")
        self.barcodeButton = QtWidgets.QPushButton(self.centralwidget)
        self.barcodeButton.setGeometry(QtCore.QRect(410, 270, 361, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.barcodeButton.setFont(font)
        self.barcodeButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/resources/img/Scanner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.barcodeButton.setIcon(icon5)
        self.barcodeButton.setIconSize(QtCore.QSize(50, 50))
        self.barcodeButton.setObjectName("barcodeButton")
        self.jerboaButton = QtWidgets.QPushButton(self.centralwidget)
        self.jerboaButton.setEnabled(False)
        self.jerboaButton.setGeometry(QtCore.QRect(20, 270, 361, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.jerboaButton.setFont(font)
        self.jerboaButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/resources/img/Jerboa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.jerboaButton.setIcon(icon6)
        self.jerboaButton.setIconSize(QtCore.QSize(50, 50))
        self.jerboaButton.setObjectName("jerboaButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.checkoutButton.clicked.connect(MainWindow.showWindow)
        self.loginButton.clicked.connect(MainWindow.loginCQC)
        self.receiptButton.clicked.connect(MainWindow.showWindow)
        self.lookupButton.clicked.connect(MainWindow.showWindow)
        self.reportButton.clicked.connect(MainWindow.showWindow)
        self.jerboaButton.clicked.connect(MainWindow.showWindow)
        self.barcodeButton.clicked.connect(MainWindow.showWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CQC Operation Tracking System - NXP Tianjin BL Quality"))
        self.about.setText(_translate("MainWindow", "<html><head/><body><p>COTS Version 0.1 Alpha</p><p>Developed by Tianjin BL Quality</p><p>Contact: van.fan@nxp.com</p></body></html>"))
        self.logo.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/resources/img/NXP.png\"/></p></body></html>"))
        self.userName.setText(_translate("MainWindow", "nxf44756"))
        self.loginLabel.setText(_translate("MainWindow", "WBI ID:\n"
"\n"
"Password:"))
        self.password.setText(_translate("MainWindow", "China#0303"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.receiptButton.setText(_translate("MainWindow", "CQC Check-in"))
        self.checkoutButton.setText(_translate("MainWindow", "CQC Check-out"))
        self.reportButton.setText(_translate("MainWindow", "CQC WIP Report"))
        self.lookupButton.setText(_translate("MainWindow", " CQC Transfer    "))
        self.barcodeButton.setText(_translate("MainWindow", "Barcode Scanner"))
        self.jerboaButton.setText(_translate("MainWindow", "Jerboa Queue"))
import qt_resource_rc
