# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\nxf44756\OneDrive - NXP\Desktop\Gadgets\COTS\source\COTS\manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(790, 670)
        Dialog.setMinimumSize(QtCore.QSize(790, 670))
        Dialog.setMaximumSize(QtCore.QSize(790, 670))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/resources/img/manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.welcomeLabel = QtWidgets.QLabel(Dialog)
        self.welcomeLabel.setGeometry(QtCore.QRect(20, 20, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.welcomeLabel.setText("")
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 60, 801, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(620, 10, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton.setObjectName("pushButton")
        self.Label_1 = QtWidgets.QLabel(Dialog)
        self.Label_1.setGeometry(QtCore.QRect(20, 80, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_1.setFont(font)
        self.Label_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Label_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label_1.setObjectName("Label_1")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(270, 70, 20, 301))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.Label_2 = QtWidgets.QLabel(Dialog)
        self.Label_2.setGeometry(QtCore.QRect(300, 80, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_2.setFont(font)
        self.Label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label_2.setObjectName("Label_2")
        self.partLabel = QtWidgets.QLabel(Dialog)
        self.partLabel.setGeometry(QtCore.QRect(360, 120, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.partLabel.setFont(font)
        self.partLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.partLabel.setText("")
        self.partLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.partLabel.setObjectName("partLabel")
        self.Label_3 = QtWidgets.QLabel(Dialog)
        self.Label_3.setGeometry(QtCore.QRect(300, 160, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_3.setFont(font)
        self.Label_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label_3.setObjectName("Label_3")
        self.peOwnerLabel = QtWidgets.QLabel(Dialog)
        self.peOwnerLabel.setGeometry(QtCore.QRect(360, 200, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.peOwnerLabel.setFont(font)
        self.peOwnerLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.peOwnerLabel.setText("")
        self.peOwnerLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.peOwnerLabel.setObjectName("peOwnerLabel")
        self.Label_4 = QtWidgets.QLabel(Dialog)
        self.Label_4.setGeometry(QtCore.QRect(300, 240, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_4.setFont(font)
        self.Label_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label_4.setObjectName("Label_4")
        self.saveRespButton = QtWidgets.QPushButton(Dialog)
        self.saveRespButton.setGeometry(QtCore.QRect(690, 110, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.saveRespButton.setFont(font)
        self.saveRespButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.saveRespButton.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 1px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    \n"
"    background-color: rgb(227, 227, 227);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.saveRespButton.setObjectName("saveRespButton")
        self.assignPEButton = QtWidgets.QPushButton(Dialog)
        self.assignPEButton.setGeometry(QtCore.QRect(300, 200, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.assignPEButton.setFont(font)
        self.assignPEButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.assignPEButton.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 1px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    \n"
"    background-color: rgb(227, 227, 227);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.assignPEButton.setObjectName("assignPEButton")
        self.addAttButton = QtWidgets.QPushButton(Dialog)
        self.addAttButton.setGeometry(QtCore.QRect(300, 280, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addAttButton.setFont(font)
        self.addAttButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.addAttButton.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 1px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    \n"
"    background-color: rgb(227, 227, 227);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.addAttButton.setObjectName("addAttButton")
        self.partSelButton = QtWidgets.QPushButton(Dialog)
        self.partSelButton.setGeometry(QtCore.QRect(300, 120, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.partSelButton.setFont(font)
        self.partSelButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.partSelButton.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 1px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    \n"
"    background-color: rgb(227, 227, 227);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.partSelButton.setObjectName("partSelButton")
        self.partAttEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.partAttEdit.setGeometry(QtCore.QRect(360, 280, 321, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.partAttEdit.setFont(font)
        self.partAttEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.partAttEdit.setPlainText("")
        self.partAttEdit.setObjectName("partAttEdit")
        self.clearOwnerButton = QtWidgets.QPushButton(Dialog)
        self.clearOwnerButton.setGeometry(QtCore.QRect(690, 200, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.clearOwnerButton.setFont(font)
        self.clearOwnerButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.clearOwnerButton.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 1px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    \n"
"    background-color: rgb(227, 227, 227);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.clearOwnerButton.setObjectName("clearOwnerButton")
        self.clearAttButton = QtWidgets.QPushButton(Dialog)
        self.clearAttButton.setGeometry(QtCore.QRect(690, 280, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.clearAttButton.setFont(font)
        self.clearAttButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.clearAttButton.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 1px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    \n"
"    background-color: rgb(227, 227, 227);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.clearAttButton.setObjectName("clearAttButton")
        self.Label_5 = QtWidgets.QLabel(Dialog)
        self.Label_5.setGeometry(QtCore.QRect(20, 160, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_5.setFont(font)
        self.Label_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label_5.setObjectName("Label_5")
        self.lookUpButton = QtWidgets.QPushButton(Dialog)
        self.lookUpButton.setGeometry(QtCore.QRect(210, 240, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lookUpButton.setFont(font)
        self.lookUpButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lookUpButton.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 1px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    \n"
"    background-color: rgb(227, 227, 227);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.lookUpButton.setObjectName("lookUpButton")
        self.Label_7 = QtWidgets.QLabel(Dialog)
        self.Label_7.setGeometry(QtCore.QRect(20, 380, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_7.setFont(font)
        self.Label_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label_7.setObjectName("Label_7")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(0, 360, 801, 20))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.saveEngButton = QtWidgets.QPushButton(Dialog)
        self.saveEngButton.setGeometry(QtCore.QRect(690, 410, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.saveEngButton.setFont(font)
        self.saveEngButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.saveEngButton.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 1px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    \n"
"    background-color: rgb(227, 227, 227);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.saveEngButton.setObjectName("saveEngButton")
        self.engInfoLabel = QtWidgets.QLabel(Dialog)
        self.engInfoLabel.setGeometry(QtCore.QRect(20, 420, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.engInfoLabel.setFont(font)
        self.engInfoLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.engInfoLabel.setText("")
        self.engInfoLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.engInfoLabel.setObjectName("engInfoLabel")
        self.Label_8 = QtWidgets.QLabel(Dialog)
        self.Label_8.setGeometry(QtCore.QRect(20, 460, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_8.setFont(font)
        self.Label_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label_8.setObjectName("Label_8")
        self.engEmailEdit = QtWidgets.QLineEdit(Dialog)
        self.engEmailEdit.setGeometry(QtCore.QRect(110, 460, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.engEmailEdit.setFont(font)
        self.engEmailEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.engEmailEdit.setText("")
        self.engEmailEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.engEmailEdit.setObjectName("engEmailEdit")
        self.Label_9 = QtWidgets.QLabel(Dialog)
        self.Label_9.setGeometry(QtCore.QRect(20, 500, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_9.setFont(font)
        self.Label_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label_9.setObjectName("Label_9")
        self.mgrEdit = QtWidgets.QLineEdit(Dialog)
        self.mgrEdit.setGeometry(QtCore.QRect(110, 500, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mgrEdit.setFont(font)
        self.mgrEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.mgrEdit.setText("")
        self.mgrEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mgrEdit.setObjectName("mgrEdit")
        self.addEngAttButton = QtWidgets.QPushButton(Dialog)
        self.addEngAttButton.setGeometry(QtCore.QRect(20, 580, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addEngAttButton.setFont(font)
        self.addEngAttButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.addEngAttButton.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 1px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    \n"
"    background-color: rgb(227, 227, 227);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.addEngAttButton.setObjectName("addEngAttButton")
        self.partAttEdit_2 = QtWidgets.QPlainTextEdit(Dialog)
        self.partAttEdit_2.setGeometry(QtCore.QRect(80, 580, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.partAttEdit_2.setFont(font)
        self.partAttEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.partAttEdit_2.setPlainText("")
        self.partAttEdit_2.setObjectName("partAttEdit_2")
        self.Label_6 = QtWidgets.QLabel(Dialog)
        self.Label_6.setGeometry(QtCore.QRect(20, 540, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_6.setFont(font)
        self.Label_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label_6.setObjectName("Label_6")
        self.clearEngAttButton = QtWidgets.QPushButton(Dialog)
        self.clearEngAttButton.setGeometry(QtCore.QRect(370, 580, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.clearEngAttButton.setFont(font)
        self.clearEngAttButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.clearEngAttButton.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 1px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    \n"
"    background-color: rgb(227, 227, 227);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.clearEngAttButton.setObjectName("clearEngAttButton")
        self.Label_10 = QtWidgets.QLabel(Dialog)
        self.Label_10.setGeometry(QtCore.QRect(380, 500, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_10.setFont(font)
        self.Label_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label_10.setObjectName("Label_10")
        self.mgrEmailEdit = QtWidgets.QLineEdit(Dialog)
        self.mgrEmailEdit.setGeometry(QtCore.QRect(480, 500, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mgrEmailEdit.setFont(font)
        self.mgrEmailEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.mgrEmailEdit.setText("")
        self.mgrEmailEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mgrEmailEdit.setObjectName("mgrEmailEdit")
        self.Label_11 = QtWidgets.QLabel(Dialog)
        self.Label_11.setGeometry(QtCore.QRect(380, 460, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_11.setFont(font)
        self.Label_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label_11.setObjectName("Label_11")
        self.partCSVButton = QtWidgets.QPushButton(Dialog)
        self.partCSVButton.setGeometry(QtCore.QRect(20, 300, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.partCSVButton.setFont(font)
        self.partCSVButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.partCSVButton.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 1px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    \n"
"    background-color: rgb(227, 227, 227);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.partCSVButton.setObjectName("partCSVButton")
        self.engCSVButton = QtWidgets.QPushButton(Dialog)
        self.engCSVButton.setGeometry(QtCore.QRect(160, 300, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.engCSVButton.setFont(font)
        self.engCSVButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.engCSVButton.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 1px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    \n"
"    background-color: rgb(227, 227, 227);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.engCSVButton.setObjectName("engCSVButton")
        self.respResultLabel = QtWidgets.QLabel(Dialog)
        self.respResultLabel.setGeometry(QtCore.QRect(550, 80, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.respResultLabel.setFont(font)
        self.respResultLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.respResultLabel.setText("")
        self.respResultLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.respResultLabel.setObjectName("respResultLabel")
        self.engResultLabel = QtWidgets.QLabel(Dialog)
        self.engResultLabel.setGeometry(QtCore.QRect(550, 380, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.engResultLabel.setFont(font)
        self.engResultLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.engResultLabel.setText("")
        self.engResultLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.engResultLabel.setObjectName("engResultLabel")
        self.partNameEdit = QtWidgets.QComboBox(Dialog)
        self.partNameEdit.setGeometry(QtCore.QRect(20, 120, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.partNameEdit.setFont(font)
        self.partNameEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.partNameEdit.setEditable(False)
        self.partNameEdit.setObjectName("partNameEdit")
        self.engineerEdit = QtWidgets.QComboBox(Dialog)
        self.engineerEdit.setGeometry(QtCore.QRect(20, 200, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.engineerEdit.setFont(font)
        self.engineerEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.engineerEdit.setEditable(False)
        self.engineerEdit.setCurrentText("")
        self.engineerEdit.setObjectName("engineerEdit")
        self.engFuncEdit = QtWidgets.QComboBox(Dialog)
        self.engFuncEdit.setGeometry(QtCore.QRect(480, 460, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.engFuncEdit.setFont(font)
        self.engFuncEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.engFuncEdit.setEditable(False)
        self.engFuncEdit.setObjectName("engFuncEdit")
        self.line_3.raise_()
        self.line_2.raise_()
        self.welcomeLabel.raise_()
        self.line.raise_()
        self.pushButton.raise_()
        self.Label_1.raise_()
        self.Label_2.raise_()
        self.partLabel.raise_()
        self.Label_3.raise_()
        self.peOwnerLabel.raise_()
        self.Label_4.raise_()
        self.saveRespButton.raise_()
        self.assignPEButton.raise_()
        self.addAttButton.raise_()
        self.partSelButton.raise_()
        self.partAttEdit.raise_()
        self.clearOwnerButton.raise_()
        self.clearAttButton.raise_()
        self.Label_5.raise_()
        self.lookUpButton.raise_()
        self.Label_7.raise_()
        self.saveEngButton.raise_()
        self.engInfoLabel.raise_()
        self.Label_8.raise_()
        self.engEmailEdit.raise_()
        self.Label_9.raise_()
        self.mgrEdit.raise_()
        self.addEngAttButton.raise_()
        self.partAttEdit_2.raise_()
        self.Label_6.raise_()
        self.clearEngAttButton.raise_()
        self.Label_10.raise_()
        self.mgrEmailEdit.raise_()
        self.Label_11.raise_()
        self.partCSVButton.raise_()
        self.engCSVButton.raise_()
        self.respResultLabel.raise_()
        self.engResultLabel.raise_()
        self.partNameEdit.raise_()
        self.engineerEdit.raise_()
        self.engFuncEdit.raise_()

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.close)
        self.lookUpButton.clicked.connect(Dialog.engineerSearch)
        self.partCSVButton.clicked.connect(Dialog.openCSV)
        self.engCSVButton.clicked.connect(Dialog.openCSV)
        self.partSelButton.clicked.connect(Dialog.partSelected)
        self.saveRespButton.clicked.connect(Dialog.saveResp)
        self.clearOwnerButton.clicked.connect(Dialog.clearEdit)
        self.clearAttButton.clicked.connect(Dialog.clearEdit)
        self.clearEngAttButton.clicked.connect(Dialog.clearEdit)
        self.saveEngButton.clicked.connect(Dialog.saveEng)
        self.assignPEButton.clicked.connect(Dialog.assignPE)
        self.addAttButton.clicked.connect(Dialog.addPartAttention)
        self.addEngAttButton.clicked.connect(Dialog.addEngAttention)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Product Manager"))
        self.pushButton.setText(_translate("Dialog", "Back to Menu"))
        self.Label_1.setText(_translate("Dialog", "Select or Create a Product"))
        self.Label_2.setText(_translate("Dialog", "Responsibility of Product"))
        self.Label_3.setText(_translate("Dialog", "Product Engineer Owner"))
        self.Label_4.setText(_translate("Dialog", "Attention"))
        self.saveRespButton.setText(_translate("Dialog", "Save"))
        self.assignPEButton.setText(_translate("Dialog", "-->"))
        self.addAttButton.setText(_translate("Dialog", "+"))
        self.partSelButton.setText(_translate("Dialog", "-->"))
        self.clearOwnerButton.setText(_translate("Dialog", "Clear"))
        self.clearAttButton.setText(_translate("Dialog", "Clear"))
        self.Label_5.setText(_translate("Dialog", "Select or Create an Engineer"))
        self.lookUpButton.setText(_translate("Dialog", "🔍"))
        self.Label_7.setText(_translate("Dialog", "Engineer Information"))
        self.saveEngButton.setText(_translate("Dialog", "Save"))
        self.Label_8.setText(_translate("Dialog", "Email"))
        self.Label_9.setText(_translate("Dialog", "Manager"))
        self.addEngAttButton.setText(_translate("Dialog", "+"))
        self.Label_6.setText(_translate("Dialog", "Attention"))
        self.clearEngAttButton.setText(_translate("Dialog", "Clear"))
        self.Label_10.setText(_translate("Dialog", "Mgr Email"))
        self.Label_11.setText(_translate("Dialog", "Function"))
        self.partCSVButton.setText(_translate("Dialog", "Open \n"
" Product CSV"))
        self.engCSVButton.setText(_translate("Dialog", "Open\n"
"Engineer CSV"))
import manager_resource_rc
