# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\nxf44756\OneDrive - NXP\Desktop\Gadgets\COTS\source\COTS\report.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1120, 640)
        Dialog.setMinimumSize(QtCore.QSize(1120, 640))
        Dialog.setMaximumSize(QtCore.QSize(1120, 640))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/resources/img/Report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(950, 10, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton.setObjectName("pushButton")
        self.cqcList = QtWidgets.QTableView(Dialog)
        self.cqcList.setGeometry(QtCore.QRect(20, 80, 1081, 461))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.cqcList.setFont(font)
        self.cqcList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cqcList.setStyleSheet("QTableView{\n"
"    selection-background-color: rgb(201, 210, 0);\n"
"}\n"
"QHeaderView::section{\n"
"    font: 75 8pt \"Calibri\";\n"
"    background-color: rgb(232, 232, 232);\n"
"}")
        self.cqcList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.cqcList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.cqcList.setProperty("showDropIndicator", False)
        self.cqcList.setDragDropOverwriteMode(False)
        self.cqcList.setAlternatingRowColors(False)
        self.cqcList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.cqcList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.cqcList.setSortingEnabled(False)
        self.cqcList.setObjectName("cqcList")
        self.cqcList.horizontalHeader().setCascadingSectionResizes(False)
        self.cqcList.horizontalHeader().setHighlightSections(False)
        self.cqcList.verticalHeader().setVisible(False)
        self.cqcList.verticalHeader().setCascadingSectionResizes(False)
        self.welcomeLabel = QtWidgets.QLabel(Dialog)
        self.welcomeLabel.setGeometry(QtCore.QRect(20, 20, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.welcomeLabel.setText("")
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.emailButton = QtWidgets.QPushButton(Dialog)
        self.emailButton.setGeometry(QtCore.QRect(980, 560, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.emailButton.setFont(font)
        self.emailButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.emailButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/resources/img/alarm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.emailButton.setIcon(icon1)
        self.emailButton.setIconSize(QtCore.QSize(40, 40))
        self.emailButton.setCheckable(False)
        self.emailButton.setObjectName("emailButton")
        self.refreshButton = QtWidgets.QPushButton(Dialog)
        self.refreshButton.setGeometry(QtCore.QRect(20, 560, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.refreshButton.setFont(font)
        self.refreshButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.refreshButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icon/resources/img/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon2)
        self.refreshButton.setIconSize(QtCore.QSize(30, 30))
        self.refreshButton.setCheckable(False)
        self.refreshButton.setObjectName("refreshButton")
        self.openButton = QtWidgets.QPushButton(Dialog)
        self.openButton.setGeometry(QtCore.QRect(500, 560, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.openButton.setFont(font)
        self.openButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.openButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icon/resources/img/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openButton.setIcon(icon3)
        self.openButton.setIconSize(QtCore.QSize(30, 30))
        self.openButton.setCheckable(False)
        self.openButton.setObjectName("openButton")
        self.resultLabel = QtWidgets.QLabel(Dialog)
        self.resultLabel.setGeometry(QtCore.QRect(650, 570, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.resultLabel.setFont(font)
        self.resultLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.resultLabel.setText("")
        self.resultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLabel.setObjectName("resultLabel")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.close)
        self.refreshButton.clicked.connect(Dialog.checkFile)
        self.openButton.clicked.connect(Dialog.openWith)
        self.emailButton.clicked.connect(Dialog.email)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "CQC WIP Report"))
        self.pushButton.setText(_translate("Dialog", "Back to Menu"))
        self.emailButton.setText(_translate("Dialog", "Send Email"))
        self.refreshButton.setText(_translate("Dialog", "   Refresh"))
        self.openButton.setText(_translate("Dialog", " Open in\n"
"Windows"))
import lookup_resource_rc
import report_resource_rc
