# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\nxf44756\OneDrive - NXP\Desktop\Gadgets\COTS\source\COTS\receipt.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1020, 500)
        Dialog.setMinimumSize(QtCore.QSize(1020, 500))
        Dialog.setMaximumSize(QtCore.QSize(1020, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/resources/img/Receipt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(860, 10, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setObjectName("pushButton")
        self.getListButton = QtWidgets.QPushButton(Dialog)
        self.getListButton.setGeometry(QtCore.QRect(10, 80, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.getListButton.setFont(font)
        self.getListButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.getListButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icon/resources/img/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.getListButton.setIcon(icon1)
        self.getListButton.setIconSize(QtCore.QSize(40, 40))
        self.getListButton.setCheckable(False)
        self.getListButton.setObjectName("getListButton")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 60, 1021, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.welcomeLabel = QtWidgets.QLabel(Dialog)
        self.welcomeLabel.setGeometry(QtCore.QRect(10, 20, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.welcomeLabel.setText("")
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(10, 470, 311, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.cqcListLable = QtWidgets.QLabel(Dialog)
        self.cqcListLable.setGeometry(QtCore.QRect(170, 80, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.cqcListLable.setFont(font)
        self.cqcListLable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cqcListLable.setText("")
        self.cqcListLable.setAlignment(QtCore.Qt.AlignCenter)
        self.cqcListLable.setObjectName("cqcListLable")
        self.cqcNumEdit = QtWidgets.QLineEdit(Dialog)
        self.cqcNumEdit.setGeometry(QtCore.QRect(10, 160, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cqcNumEdit.setFont(font)
        self.cqcNumEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cqcNumEdit.setText("")
        self.cqcNumEdit.setMaxLength(7)
        self.cqcNumEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cqcNumEdit.setObjectName("cqcNumEdit")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(320, 70, 16, 421))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(10, 130, 311, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(10, 140, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 200, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.partNameEdit = QtWidgets.QLineEdit(Dialog)
        self.partNameEdit.setGeometry(QtCore.QRect(10, 220, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.partNameEdit.setFont(font)
        self.partNameEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.partNameEdit.setText("")
        self.partNameEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.partNameEdit.setObjectName("partNameEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 260, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.cqeEdit = QtWidgets.QLineEdit(Dialog)
        self.cqeEdit.setGeometry(QtCore.QRect(10, 280, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.cqeEdit.setFont(font)
        self.cqeEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cqeEdit.setText("")
        self.cqeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cqeEdit.setObjectName("cqeEdit")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 320, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.peEdit = QtWidgets.QLineEdit(Dialog)
        self.peEdit.setGeometry(QtCore.QRect(10, 340, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.peEdit.setFont(font)
        self.peEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.peEdit.setText("")
        self.peEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.peEdit.setObjectName("peEdit")
        self.prpBox = QtWidgets.QCheckBox(Dialog)
        self.prpBox.setGeometry(QtCore.QRect(190, 210, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.prpBox.setFont(font)
        self.prpBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prpBox.setChecked(True)
        self.prpBox.setObjectName("prpBox")
        self.rcvBox = QtWidgets.QCheckBox(Dialog)
        self.rcvBox.setGeometry(QtCore.QRect(190, 170, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rcvBox.setFont(font)
        self.rcvBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rcvBox.setChecked(True)
        self.rcvBox.setObjectName("rcvBox")
        self.printBox = QtWidgets.QCheckBox(Dialog)
        self.printBox.setGeometry(QtCore.QRect(190, 250, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.printBox.setFont(font)
        self.printBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.printBox.setChecked(True)
        self.printBox.setObjectName("printBox")
        self.checkOnlyBox = QtWidgets.QCheckBox(Dialog)
        self.checkOnlyBox.setGeometry(QtCore.QRect(190, 290, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.checkOnlyBox.setFont(font)
        self.checkOnlyBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkOnlyBox.setObjectName("checkOnlyBox")
        self.checkinButton = QtWidgets.QPushButton(Dialog)
        self.checkinButton.setGeometry(QtCore.QRect(190, 340, 111, 91))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkinButton.setFont(font)
        self.checkinButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkinButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icon/resources/img/check-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkinButton.setIcon(icon2)
        self.checkinButton.setIconSize(QtCore.QSize(40, 40))
        self.checkinButton.setCheckable(False)
        self.checkinButton.setObjectName("checkinButton")
        self.resultLabel = QtWidgets.QLabel(Dialog)
        self.resultLabel.setGeometry(QtCore.QRect(10, 440, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.resultLabel.setFont(font)
        self.resultLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.resultLabel.setText("")
        self.resultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLabel.setObjectName("resultLabel")
        self.instruEdit = QtWidgets.QLineEdit(Dialog)
        self.instruEdit.setGeometry(QtCore.QRect(10, 400, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.instruEdit.setFont(font)
        self.instruEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.instruEdit.setText("")
        self.instruEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.instruEdit.setObjectName("instruEdit")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 380, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.cqcList = QtWidgets.QTableView(Dialog)
        self.cqcList.setGeometry(QtCore.QRect(340, 80, 671, 401))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.cqcList.setFont(font)
        self.cqcList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cqcList.setStyleSheet("QTableView{\n"
"    selection-background-color: rgb(201, 210, 0);\n"
"}\n"
"QHeaderView::section{\n"
"    font: 75 8pt \"Arial\";\n"
"    background-color: rgb(232, 232, 232);\n"
"}")
        self.cqcList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.cqcList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.cqcList.setProperty("showDropIndicator", False)
        self.cqcList.setDragDropOverwriteMode(False)
        self.cqcList.setAlternatingRowColors(False)
        self.cqcList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.cqcList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.cqcList.setSortingEnabled(False)
        self.cqcList.setObjectName("cqcList")
        self.cqcList.horizontalHeader().setCascadingSectionResizes(False)
        self.cqcList.horizontalHeader().setHighlightSections(False)
        self.cqcList.verticalHeader().setVisible(False)
        self.cqcList.verticalHeader().setCascadingSectionResizes(False)

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.close)
        self.getListButton.clicked.connect(Dialog.getCqcList)
        self.checkinButton.clicked.connect(Dialog.checkin)
        self.cqcList.doubleClicked['QModelIndex'].connect(Dialog.itemSelected)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "CQC Receipt"))
        self.pushButton.setText(_translate("Dialog", "Back to Menu"))
        self.getListButton.setText(_translate("Dialog", "Update CQC List"))
        self.label_1.setText(_translate("Dialog", "CQC Number"))
        self.label_2.setText(_translate("Dialog", "Part Name"))
        self.label_3.setText(_translate("Dialog", "Quality Engineer"))
        self.label_4.setText(_translate("Dialog", "Product Engineer"))
        self.prpBox.setText(_translate("Dialog", "Create PRP"))
        self.rcvBox.setText(_translate("Dialog", "Close RCV/RCT"))
        self.printBox.setText(_translate("Dialog", "Print Label"))
        self.checkOnlyBox.setText(_translate("Dialog", "Check-in Only"))
        self.checkinButton.setText(_translate("Dialog", "Check-in"))
        self.label_5.setText(_translate("Dialog", "Instruction"))
import receipt_resource_rc
